# -----------------------------------
# Dockerfile (pour personnaliser exo)
# -----------------------------------
FROM exoplatform/exo-community:7.0.0

# Copie du module dans le conteneur (en fonction de vos chemin d'acces)
COPY ./demande-conge-extension-services.jar /opt/exo/lib
COPY ./demande-conge-extension-webapp.war /opt/exo/webapp